### ISSUE TITLE
console is not defined

### ISSUE THREAD

**Issue by garethbowen** [nolanlawson/worker-pouch#16]
Using worker-pouch I'm getting random pouch calls failing with "console is not defined".

![eed4b2e8-1607-11e6-8b3b-f6cd9b3d7bf7](https://cloud.githubusercontent.com/assets/2064938/15356790/0ede929a-1d4f-11e6-81ff-ac72cbfecce0.png)

This happens on Chrome v30 which is what the webview for android 4.4.2 is locked to. I can't reproduce on Firefox or Chrome latest. I _think_ this is due to the `console` not being defined in web workers in this version of Chrome.

I assume this is due to something in PouchDB logging but it's very difficult to test and debug, so I can't tell for sure.

Maybe the fix is some sort of console polyfill (eg: https://github.com/padolsey/operative/blob/master/src/contexts/BrowserWorker.js#L189) or maybe just a console stub so log messages are ignored.

**Comment by nolanlawson** [comment]
released in 1.0.3, fixed (hopefully) in #17

**Comment by garethbowen** [comment]
I can still reproduce this with 1.0.3 :(

**Comment by nolanlawson** [comment]
Seems it's an issue in core Pouch, then. :/

**Comment by garethbowen** [comment]
Could be. It could be in core or a plugin, right? That's why I leaned towards using the no-op polyfill.

**Comment by nolanlawson** [comment]
It could be in [a lot of places](https://github.com/pouchdb/pouchdb/search?utf8=%E2%9C%93&q=console). I admit such a bug may be lurking in PouchDB's code base, because we can't test Android <4.4 in SauceLabs and also don't test <4.4 in a worker.

The no-op polyfill sounds like a good solution for your codebase if you're not sure where the console is coming from though.

**Comment by garethbowen** [comment]
> The no-op polyfill sounds like a good solution...

Does that mean you'll consider reopening https://github.com/nolanlawson/worker-pouch/pull/18 ?

**Comment by nolanlawson** [comment]
I'd prefer not to have a global polyfill in a library. It's the same policy we normally take with Promises, etc. IMO it's best to handle `console` on a case-by-case basis rather than pollute the global namespace, since it's less surprising for users.

OTOH PouchDB claims to run in Android 4+, so it's reasonable to put `console` guards in there. I think we just need to comb the codebase and wrap all the `console` usages.

**Comment by nolanlawson** [comment]
I did mean it might be a good solution for your own project though.

**Comment by garethbowen** [comment]
I don't think I can add it in my project though because I don't have access to the worker. It's only the worker "global" I'm polluting, not the actual "global". I'm happy to comb through PouchDB and fix any I find. I worry that a later version of PouchDB or a plugin might add unguarded console logs, as you say it can't be CI tested.

How do you feel about passing a flag to opt in to legacy support?

The only other way I can see to do it is to fork worker-pouch and that doesn't help anyone else.

**Comment by nolanlawson** [comment]
worker-pouch now has a "custom mode" that allows you to use its code inside your own worker, so you could use that to inject a global `console`.

**Comment by garethbowen** [comment]
I got the "custom mode" solution working today. Thanks @nolanlawson !
